spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car_parking_management_system?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=Europe/Sofia
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_CLIENT_ID
            client-secret: YOUR_CLIENT_SECRET
            redirect-uri: YOUR_CLIENT_REDIRECT_URI
  mail:
    host: smtp.gmail.com
    port: 587
    username: YOUR_MAIL
    password: 2FACTOR_PASSWORD
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: true

logging:
  level:
    org.springframework.security: DEBUG



server:
  port: ${port:8081}
